sudo: required
language: generic

services:
  - docker

before_install:
  - export KOHA_VER="$(cat Koha.pm | grep '$VERSION =')" && export KOHA_VER=${KOHA_VER%\"*} && export KOHA_VER=${KOHA_VER##*\"} && echo $KOHA_VER
  # Grab the Koha version from Koha.pm
  - IFS='.' read -ra VER_PARTS <<< "$KOHA_VER"
  - export KOHA_MAJOR=${VER_PARTS[0]}
  - export KOHA_MINOR=${VER_PARTS[1]}
  # If the minor version is even, assume we are on master
  - if [ $((KOHA_MINOR%2)) -eq 0 ]; then export KOHA_BRANCH='master'; else export KOHA_BRANCH="$KOHA_MAJOR.$KOHA_MINOR"; fi
  - echo $KOHA_MAJOR
  - echo $KOHA_MINOR
  - echo $KOHA_BRANCH
  - cd .. # Now set up koha-testing-docker
  - ls -alh
  - pwd
  - export SYNC_REPO=/home/travis/build/bywatersolutions/bywater-koha # Needed for koha-testing-docker
  - export LOCAL_USER_ID="$(id -u)" # Needed for koha-testing-docker
  - git clone https://github.com/tomascohen/koha-testing-docker.git
  - cd koha-testing-docker
  - git checkout origin/${KOHA_BRANCH} # Check out the correct koha-testing-docker branch
  - docker-compose build
  - sudo sysctl -w vm.max_map_count=262144

script:
  - docker-compose down
  - docker-compose run koha
  - cat /home/travis/build/bywatersolutions/bywater-koha/testing.success
